### ISSUE TITLE
[Library Plugin] Support Kotlin Multiplatform modules

### ISSUE THREAD

**Issue by EdricChan03** [EdricChan03/androidx-ktx-extras#15]
For #14 

## Tasks

* [x] Extract common top-level Kotlin configuration (done in https://github.com/EdricChan03/androidx-ktx-extras/commit/c067e5ddb5841f70f1325f9df3186c2120fef2e2)
* [ ] Disable Android variant publication on KMP modules
  * [ ] Add suitable conventions for the `libraryType` Gradle lazy property
* [ ] Additional config for KMP, if any
